export function feishuHelpText() {
  return [
    "OMP 后台命令（在 OMP 中运行）：",
    "/feishu setup - 配置飞书应用",
    "/feishu start - 启动飞书连接",
    "/feishu stop - 停止飞书连接",
    "/feishu restart - 重启连接并加载最新代码和配置",
    "/feishu autostart - 开关自动启动",
    "/feishu reset - 重置插件配置和会话映射",
    "",
    "飞书聊天命令（直接发给机器人）：",
    "/feishu help 或 /help - 查看全部命令及用途",
    "/feishu doctor 或 /doctor - 检查配置、OMP、模型和 daemon",
    "/feishu version 或 /version - 查看插件、OMP 和 Bun 版本",
    "/feishu upgrade - 升级插件到最新版（可指定版本：/feishu upgrade 0.4.14）",
    "/feishu status - 查看连接状态和运行位置",
    "/feishu config - 查看脱敏配置（管理员）",
    "/feishu debug - 查看最近的调试日志（管理员）",
    "/feishu refresh - 刷新 OMP 模型列表（管理员）",
    "/new - 新建当前飞书会话",
    "/resume - 恢复当前聊天的历史会话",
    "/model - 选择当前聊天使用的模型",
    "/stop - 停止当前聊天正在执行的任务",
    "/workspace PATH - 切换当前聊天的工作目录（管理员）",
    "/send PATH - 发送当前工作区内的文件或图片（管理员）",
    "自动发送 - OMP 任务完成后，自动把生成的图片、文档、音频发回当前飞书会话",
  ].join("\n");
}
